// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using NDesk.DBus;

using Gtk;
using Gdk;

namespace DBusExplorer
{
	public partial class DBusMonitor : Gtk.Dialog
	{
		Bus bus;
		ObjectPath path;
		
		TextBuffer   buffer;
		TextTagTable table = new TextTagTable();
		
		public DBusMonitor(Bus bus, ObjectPath path) {
			this.bus  = bus;
			this.path = path;
			this.Build();
			
			InitTextTags();
			buffer = new TextBuffer(table);
			this.monitor_tv.Buffer = buffer;
		}
		
		void InitTextTags()
		{
			TextTag methodCall = new TextTag("methodCall");
			TextTag methodReturn = new TextTag("methodReturn");
			TextTag signal = new TextTag("signal");
			
			table.Add(methodCall);
			table.Add(methodReturn);
			table.Add(signal);
		}
		
		void AddLog(string log, string tag)
		{
		
		}
	}
}
