
// This file has been generated by the GUI designer. Do not modify.
namespace DBusExplorer
{
	public partial class GenerationDialog
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Label label1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView selectionTv;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label3;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Label countLabel;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button selectAllButton;

		private global::Gtk.Button unselectAllButton;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView codeTextView;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button clipboardCopy;

		private global::Gtk.Button buttonClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DBusExplorer.GenerationDialog
			this.Name = "DBusExplorer.GenerationDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Generation dialog");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultHeight = 300;
			// Internal child DBusExplorer.GenerationDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(9));
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Select the members you want to export</b>");
			this.label1.UseMarkup = true;
			this.alignment1.Add (this.label1);
			this.vbox2.Add (this.alignment1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.HeightRequest = 210;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.selectionTv = new global::Gtk.TreeView ();
			this.selectionTv.CanFocus = true;
			this.selectionTv.Name = "selectionTv";
			this.selectionTv.HeadersVisible = false;
			this.GtkScrolledWindow.Add (this.selectionTv);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w5.Position = 1;
			w5.Padding = ((uint)(2));
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment2.Name = "alignment2";
			this.alignment2.BottomPadding = ((uint)(20));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Total:");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment3.Name = "alignment3";
			// Container child alignment3.Gtk.Container+ContainerChild
			this.countLabel = new global::Gtk.Label ();
			this.countLabel.Name = "countLabel";
			this.countLabel.Xalign = 0f;
			this.countLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.alignment3.Add (this.countLabel);
			this.hbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment3]));
			w8.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.selectAllButton = new global::Gtk.Button ();
			this.selectAllButton.CanFocus = true;
			this.selectAllButton.Name = "selectAllButton";
			this.selectAllButton.UseStock = true;
			this.selectAllButton.UseUnderline = true;
			this.selectAllButton.Label = "gtk-select-all";
			this.hbox2.Add (this.selectAllButton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.selectAllButton]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.unselectAllButton = new global::Gtk.Button ();
			this.unselectAllButton.CanFocus = true;
			this.unselectAllButton.Name = "unselectAllButton";
			this.unselectAllButton.UseUnderline = true;
			this.unselectAllButton.Label = global::Mono.Unix.Catalog.GetString ("Unselect all");
			this.hbox2.Add (this.unselectAllButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.unselectAllButton]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.alignment4.Add (this.hbox2);
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment4]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.alignment2.Add (this.hbox1);
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment2]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.codeTextView = new global::Gtk.TextView ();
			this.codeTextView.HeightRequest = 200;
			this.codeTextView.CanFocus = true;
			this.codeTextView.Name = "codeTextView";
			this.codeTextView.Editable = false;
			this.codeTextView.AcceptsTab = false;
			this.GtkScrolledWindow1.Add (this.codeTextView);
			this.vbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
			w16.Position = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment5.Name = "alignment5";
			// Container child alignment5.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.clipboardCopy = new global::Gtk.Button ();
			this.clipboardCopy.CanFocus = true;
			this.clipboardCopy.Name = "clipboardCopy";
			this.clipboardCopy.UseUnderline = true;
			this.clipboardCopy.Label = global::Mono.Unix.Catalog.GetString ("_Copy to clipboard");
			this.hbox3.Add (this.clipboardCopy);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.clipboardCopy]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			this.alignment5.Add (this.hbox3);
			this.vbox2.Add (this.alignment5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment5]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w20.Position = 0;
			w20.Expand = false;
			// Internal child DBusExplorer.GenerationDialog.ActionArea
			global::Gtk.HButtonBox w21 = this.ActionArea;
			w21.Name = "dialog1_ActionArea";
			w21.Spacing = 6;
			w21.BorderWidth = ((uint)(5));
			w21.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button ();
			this.buttonClose.CanDefault = true;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseStock = true;
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = "gtk-close";
			this.AddActionWidget (this.buttonClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21[this.buttonClose]));
			w22.Expand = false;
			w22.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 680;
			this.Show ();
			this.selectAllButton.Clicked += new global::System.EventHandler (this.OnSelectAllButtonClicked);
			this.unselectAllButton.Clicked += new global::System.EventHandler (this.OnUnselectAllButtonClicked);
			this.clipboardCopy.Clicked += new global::System.EventHandler (this.OnClipboardCopyClicked);
		}
	}
}
