
// This file has been generated by the GUI designer. Do not modify.
namespace DBusExplorer
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action SelectBus;

		private global::Gtk.RadioAction SessionBus;

		private global::Gtk.RadioAction SystemBus;

		private global::Gtk.Action quit;

		private global::Gtk.Action quit1;

		private global::Gtk.Action Help;

		private global::Gtk.Action about;

		private global::Gtk.Action View;

		private global::Gtk.Action CustomBus;

		private global::Gtk.Action Tools;

		private global::Gtk.Action Languages;

		private global::Gtk.ToggleAction C;

		private global::Gtk.Action NewTabAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Alignment busCbCont;

		private global::Gtk.ComboBox busCb;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.HBox spinnerBox;

		private global::Gtk.Alignment spinnerAlign;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.Label label4;

		private global::Gtk.Notebook buses_Nb;

		private global::Gtk.Label label2;

		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DBusExplorer.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
			w1.Add (this.FileAction, null);
			this.SelectBus = new global::Gtk.Action ("SelectBus", global::Mono.Unix.Catalog.GetString ("_Select Bus"), null, null);
			this.SelectBus.ShortLabel = global::Mono.Unix.Catalog.GetString ("Select Bus");
			w1.Add (this.SelectBus, "<Control><Mod2>s");
			this.SessionBus = new global::Gtk.RadioAction ("SessionBus", global::Mono.Unix.Catalog.GetString ("S_ession Bus"), null, null, 0);
			this.SessionBus.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.SessionBus.ShortLabel = global::Mono.Unix.Catalog.GetString ("Session Bus");
			w1.Add (this.SessionBus, null);
			this.SystemBus = new global::Gtk.RadioAction ("SystemBus", global::Mono.Unix.Catalog.GetString ("S_ystem Bus"), null, null, 0);
			this.SystemBus.Group = this.SessionBus.Group;
			this.SystemBus.ShortLabel = global::Mono.Unix.Catalog.GetString ("System Bus");
			w1.Add (this.SystemBus, null);
			this.quit = new global::Gtk.Action ("quit", global::Mono.Unix.Catalog.GetString ("_Quitter"), null, "gtk-quit");
			this.quit.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quitter");
			w1.Add (this.quit, null);
			this.quit1 = new global::Gtk.Action ("quit1", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
			this.quit1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
			w1.Add (this.quit1, null);
			this.Help = new global::Gtk.Action ("Help", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
			this.Help.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.Help, null);
			this.about = new global::Gtk.Action ("about", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-about");
			this.about.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
			w1.Add (this.about, null);
			this.View = new global::Gtk.Action ("View", global::Mono.Unix.Catalog.GetString ("_View"), null, null);
			this.View.ShortLabel = global::Mono.Unix.Catalog.GetString ("_View");
			w1.Add (this.View, null);
			this.CustomBus = new global::Gtk.Action ("CustomBus", global::Mono.Unix.Catalog.GetString ("C_ustom Bus..."), null, null);
			this.CustomBus.ShortLabel = global::Mono.Unix.Catalog.GetString ("C_ustom Bus...");
			w1.Add (this.CustomBus, null);
			this.Tools = new global::Gtk.Action ("Tools", global::Mono.Unix.Catalog.GetString ("_Tools"), null, null);
			this.Tools.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Tools");
			w1.Add (this.Tools, null);
			this.Languages = new global::Gtk.Action ("Languages", global::Mono.Unix.Catalog.GetString ("Languages"), null, null);
			this.Languages.ShortLabel = global::Mono.Unix.Catalog.GetString ("Languages");
			w1.Add (this.Languages, null);
			this.C = new global::Gtk.ToggleAction ("C", global::Mono.Unix.Catalog.GetString ("C#"), null, null);
			this.C.ShortLabel = global::Mono.Unix.Catalog.GetString ("C#");
			w1.Add (this.C, null);
			this.NewTabAction = new global::Gtk.Action ("NewTabAction", global::Mono.Unix.Catalog.GetString ("New _tab"), null, null);
			this.NewTabAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New _tab");
			w1.Add (this.NewTabAction, "<Control><Mod2>t");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "DBusExplorer.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("D-Bus Explorer");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("DBusExplorer.data.dbus-explorer.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.DefaultHeight = 600;
			// Container child DBusExplorer.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='NewTabAction' action='NewTabAction'/><menu name='SelectBus' action='SelectBus'><menuitem name='SessionBus' action='SessionBus'/><menuitem name='SystemBus' action='SystemBus'/><menuitem name='CustomBus' action='CustomBus'/></menu><menuitem name='quit1' action='quit1'/></menu><menu name='Help' action='Help'><menuitem name='about' action='about'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(5));
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Bus name : ");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(6));
			// Container child hbox1.Gtk.Box+BoxChild
			this.busCbCont = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.busCbCont.Name = "busCbCont";
			// Container child busCbCont.Gtk.Container+ContainerChild
			this.busCb = global::Gtk.ComboBox.NewText ();
			this.busCb.Name = "busCb";
			this.busCbCont.Add (this.busCb);
			this.hbox1.Add (this.busCbCont);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.busCbCont]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment4.Name = "alignment4";
			this.alignment4.LeftPadding = ((uint)(62));
			this.alignment4.RightPadding = ((uint)(208));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.spinnerBox = new global::Gtk.HBox ();
			this.spinnerBox.Name = "spinnerBox";
			this.spinnerBox.Spacing = 6;
			// Container child spinnerBox.Gtk.Box+BoxChild
			this.spinnerAlign = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.spinnerAlign.Name = "spinnerAlign";
			this.spinnerBox.Add (this.spinnerAlign);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.spinnerBox[this.spinnerAlign]));
			w6.Position = 0;
			// Container child spinnerBox.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment6.Name = "alignment6";
			// Container child alignment6.Gtk.Container+ContainerChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Parsing ...");
			this.alignment6.Add (this.label4);
			this.spinnerBox.Add (this.alignment6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.spinnerBox[this.alignment6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.alignment4.Add (this.spinnerBox);
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment4]));
			w10.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(1));
			// Container child vbox1.Gtk.Box+BoxChild
			this.buses_Nb = new global::Gtk.Notebook ();
			this.buses_Nb.CanFocus = true;
			this.buses_Nb.Name = "buses_Nb";
			this.buses_Nb.CurrentPage = 0;
			this.buses_Nb.BorderWidth = ((uint)(3));
			// Notebook tab
			global::Gtk.Label w12 = new global::Gtk.Label ();
			w12.Visible = true;
			this.buses_Nb.Add (w12);
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("(No Title)");
			this.buses_Nb.SetTabLabel (w12, this.label2);
			this.label2.ShowAll ();
			this.vbox1.Add (this.buses_Nb);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buses_Nb]));
			w13.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 798;
			this.Show ();
			this.SessionBus.Activated += new global::System.EventHandler (this.OnSessionBusActivated);
			this.SystemBus.Activated += new global::System.EventHandler (this.OnSystemBusActivated);
			this.quit.Activated += new global::System.EventHandler (this.OnDeleteEvent);
			this.quit1.Activated += new global::System.EventHandler (this.OnDeleteEvent);
			this.about.Activated += new global::System.EventHandler (this.OnAboutActivated);
			this.CustomBus.Activated += new global::System.EventHandler (this.OnCustomBusActivated);
			this.NewTabAction.Activated += new global::System.EventHandler (this.OnNewTabActionActivated);
			this.buses_Nb.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnBusesNbSwitchPage);
		}
	}
}
