// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    public partial class LanguageWidget {
        
        private Gtk.EventBox evts;
        
        private Gtk.Table table;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.LanguageWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "DBusExplorer.LanguageWidget";
            // Container child DBusExplorer.LanguageWidget.Gtk.Container+ContainerChild
            this.evts = new Gtk.EventBox();
            this.evts.Name = "evts";
            // Container child evts.Gtk.Container+ContainerChild
            this.table = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table.Name = "table";
            this.table.RowSpacing = ((uint)(6));
            this.table.ColumnSpacing = ((uint)(6));
            this.evts.Add(this.table);
            this.Add(this.evts);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
