// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    
    public partial class InvokeDialog {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Label methodName;
        
        private Gtk.VBox argsVb;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label3;
        
        private Gtk.Label resultLabel;
        
        private Gtk.Button buttonExecute;
        
        private Gtk.Button buttonClose;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.InvokeDialog
            this.Name = "DBusExplorer.InvokeDialog";
            this.Title = Mono.Unix.Catalog.GetString("Method call dialog");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child DBusExplorer.InvokeDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(3));
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(6));
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Invocation of method :");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            w2.Padding = ((uint)(17));
            // Container child hbox1.Gtk.Box+BoxChild
            this.methodName = new Gtk.Label();
            this.methodName.Name = "methodName";
            this.methodName.LabelProp = Mono.Unix.Catalog.GetString("label2");
            this.methodName.UseMarkup = true;
            this.hbox1.Add(this.methodName);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.methodName]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            w4.Padding = ((uint)(4));
            // Container child vbox2.Gtk.Box+BoxChild
            this.argsVb = new Gtk.VBox();
            this.argsVb.Name = "argsVb";
            this.argsVb.Spacing = 6;
            this.argsVb.BorderWidth = ((uint)(6));
            this.vbox2.Add(this.argsVb);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.argsVb]));
            w5.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            this.hbox2.BorderWidth = ((uint)(6));
            // Container child hbox2.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("<b>Result : </b>");
            this.label3.UseMarkup = true;
            this.hbox2.Add(this.label3);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.label3]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            w6.Padding = ((uint)(16));
            // Container child hbox2.Gtk.Box+BoxChild
            this.resultLabel = new Gtk.Label();
            this.resultLabel.Name = "resultLabel";
            this.hbox2.Add(this.resultLabel);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.resultLabel]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            w8.Padding = ((uint)(4));
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w9.Position = 0;
            // Internal child DBusExplorer.InvokeDialog.ActionArea
            Gtk.HButtonBox w10 = this.ActionArea;
            w10.Name = "dialog1_ActionArea";
            w10.Spacing = 6;
            w10.BorderWidth = ((uint)(5));
            w10.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonExecute = new Gtk.Button();
            this.buttonExecute.CanDefault = true;
            this.buttonExecute.CanFocus = true;
            this.buttonExecute.Name = "buttonExecute";
            this.buttonExecute.UseStock = true;
            this.buttonExecute.UseUnderline = true;
            this.buttonExecute.Label = "gtk-execute";
            w10.Add(this.buttonExecute);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonExecute]));
            w11.Expand = false;
            w11.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonClose = new Gtk.Button();
            this.buttonClose.CanFocus = true;
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.UseStock = true;
            this.buttonClose.UseUnderline = true;
            this.buttonClose.Label = "gtk-close";
            this.AddActionWidget(this.buttonClose, -7);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonClose]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 276;
            this.DefaultHeight = 164;
            this.Show();
            this.buttonExecute.Activated += new System.EventHandler(this.OnButtonExecuteActivated);
        }
    }
}
