// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    
    public partial class PropertyInvokeDialog {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Label propName;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.RadioButton getBtn;
        
        private Gtk.RadioButton setBtn;
        
        private Gtk.Alignment actionAlign;
        
        private Gtk.Alignment getAlign;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label2;
        
        private Gtk.Alignment alignment6;
        
        private Gtk.Entry setEntry;
        
        private Gtk.Alignment setAlign;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label label3;
        
        private Gtk.Alignment alignment7;
        
        private Gtk.Label getLbl;
        
        private Gtk.Button buttonExecute;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.PropertyInvokeDialog
            this.Name = "DBusExplorer.PropertyInvokeDialog";
            this.Title = Mono.Unix.Catalog.GetString("Property invoke dialog");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child DBusExplorer.PropertyInvokeDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            this.vbox2.BorderWidth = ((uint)(3));
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(6));
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Invocation of property :");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            w2.Padding = ((uint)(17));
            // Container child hbox1.Gtk.Box+BoxChild
            this.propName = new Gtk.Label();
            this.propName.Name = "propName";
            this.propName.LabelProp = Mono.Unix.Catalog.GetString("label2");
            this.propName.UseMarkup = true;
            this.hbox1.Add(this.propName);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.propName]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            w4.Padding = ((uint)(4));
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.getBtn = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("get"));
            this.getBtn.CanFocus = true;
            this.getBtn.Name = "getBtn";
            this.getBtn.DrawIndicator = true;
            this.getBtn.UseUnderline = true;
            this.getBtn.Group = new GLib.SList(System.IntPtr.Zero);
            this.hbox2.Add(this.getBtn);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.getBtn]));
            w5.Position = 0;
            w5.Expand = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.setBtn = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("set"));
            this.setBtn.CanFocus = true;
            this.setBtn.Name = "setBtn";
            this.setBtn.DrawIndicator = true;
            this.setBtn.UseUnderline = true;
            this.setBtn.Group = this.getBtn.Group;
            this.hbox2.Add(this.setBtn);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.setBtn]));
            w6.Position = 1;
            this.alignment1.Add(this.hbox2);
            this.vbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.actionAlign = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.actionAlign.Name = "actionAlign";
            // Container child actionAlign.Gtk.Container+ContainerChild
            this.getAlign = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.getAlign.Name = "getAlign";
            // Container child getAlign.Gtk.Container+ContainerChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("New value :");
            this.hbox3.Add(this.label2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.label2]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.alignment6 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment6.Name = "alignment6";
            // Container child alignment6.Gtk.Container+ContainerChild
            this.setEntry = new Gtk.Entry();
            this.setEntry.CanFocus = true;
            this.setEntry.Name = "setEntry";
            this.setEntry.IsEditable = true;
            this.setEntry.InvisibleChar = '•';
            this.alignment6.Add(this.setEntry);
            this.hbox3.Add(this.alignment6);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox3[this.alignment6]));
            w11.Position = 1;
            this.getAlign.Add(this.hbox3);
            this.actionAlign.Add(this.getAlign);
            this.vbox2.Add(this.actionAlign);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox2[this.actionAlign]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            w14.Padding = ((uint)(4));
            // Container child vbox2.Gtk.Box+BoxChild
            this.setAlign = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.setAlign.Name = "setAlign";
            // Container child setAlign.Gtk.Container+ContainerChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Current value :");
            this.hbox4.Add(this.label3);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox4[this.label3]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.alignment7 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment7.Name = "alignment7";
            // Container child alignment7.Gtk.Container+ContainerChild
            this.getLbl = new Gtk.Label();
            this.getLbl.Name = "getLbl";
            this.getLbl.LabelProp = Mono.Unix.Catalog.GetString("label4");
            this.alignment7.Add(this.getLbl);
            this.hbox4.Add(this.alignment7);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox4[this.alignment7]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            this.setAlign.Add(this.hbox4);
            this.vbox2.Add(this.setAlign);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.setAlign]));
            w19.Position = 3;
            w19.Expand = false;
            w19.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Internal child DBusExplorer.PropertyInvokeDialog.ActionArea
            Gtk.HButtonBox w21 = this.ActionArea;
            w21.Name = "dialog1_ActionArea";
            w21.Spacing = 6;
            w21.BorderWidth = ((uint)(5));
            w21.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonExecute = new Gtk.Button();
            this.buttonExecute.CanDefault = true;
            this.buttonExecute.CanFocus = true;
            this.buttonExecute.Name = "buttonExecute";
            this.buttonExecute.UseStock = true;
            this.buttonExecute.UseUnderline = true;
            this.buttonExecute.Label = "gtk-execute";
            w21.Add(this.buttonExecute);
            Gtk.ButtonBox.ButtonBoxChild w22 = ((Gtk.ButtonBox.ButtonBoxChild)(w21[this.buttonExecute]));
            w22.Expand = false;
            w22.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-close";
            this.AddActionWidget(this.buttonOk, -7);
            Gtk.ButtonBox.ButtonBoxChild w23 = ((Gtk.ButtonBox.ButtonBoxChild)(w21[this.buttonOk]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 282;
            this.DefaultHeight = 205;
            this.Show();
            this.getBtn.Toggled += new System.EventHandler(this.OnGetBtnToggled);
            this.setBtn.Toggled += new System.EventHandler(this.OnSetBtnToggled);
            this.buttonExecute.Clicked += new System.EventHandler(this.OnButtonExecuteClicked);
        }
    }
}
