// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    
    public partial class MainWindow {
        
        private Gtk.Action File;
        
        private Gtk.Action SelectBus;
        
        private Gtk.RadioAction SessionBus;
        
        private Gtk.RadioAction SystemBus;
        
        private Gtk.Action quit;
        
        private Gtk.Action quit1;
        
        private Gtk.Action Help;
        
        private Gtk.Action about;
        
        private Gtk.Action View;
        
        private Gtk.Action Monitor;
        
        private Gtk.Action CustomBus;
        
        private Gtk.Action Tools;
        
        private Gtk.Action Languages;
        
        private Gtk.ToggleAction C;
        
        private Gtk.Action NewTabAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Alignment busCbCont;
        
        private Gtk.ComboBox busCb;
        
        private Gtk.Alignment alignment4;
        
        private Gtk.HBox spinnerBox;
        
        private Gtk.Alignment spinnerAlign;
        
        private Gtk.Alignment alignment6;
        
        private Gtk.Label label4;
        
        private Gtk.Notebook buses_Nb;
        
        private Gtk.Label label2;
        
        private Gtk.Statusbar statusbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("_File"), null, null);
            this.File.ShortLabel = Mono.Unix.Catalog.GetString("_File");
            w2.Add(this.File, null);
            this.SelectBus = new Gtk.Action("SelectBus", Mono.Unix.Catalog.GetString("_Select Bus"), null, null);
            this.SelectBus.ShortLabel = Mono.Unix.Catalog.GetString("Select Bus");
            w2.Add(this.SelectBus, null);
            this.SessionBus = new Gtk.RadioAction("SessionBus", Mono.Unix.Catalog.GetString("S_ession Bus"), null, null, 0);
            this.SessionBus.Group = new GLib.SList(System.IntPtr.Zero);
            this.SessionBus.ShortLabel = Mono.Unix.Catalog.GetString("Session Bus");
            w2.Add(this.SessionBus, null);
            this.SystemBus = new Gtk.RadioAction("SystemBus", Mono.Unix.Catalog.GetString("S_ystem Bus"), null, null, 0);
            this.SystemBus.Group = this.SessionBus.Group;
            this.SystemBus.ShortLabel = Mono.Unix.Catalog.GetString("System Bus");
            w2.Add(this.SystemBus, null);
            this.quit = new Gtk.Action("quit", Mono.Unix.Catalog.GetString("_Quitter"), null, "gtk-quit");
            this.quit.ShortLabel = Mono.Unix.Catalog.GetString("_Quitter");
            w2.Add(this.quit, null);
            this.quit1 = new Gtk.Action("quit1", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
            this.quit1.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
            w2.Add(this.quit1, null);
            this.Help = new Gtk.Action("Help", Mono.Unix.Catalog.GetString("_Help"), null, null);
            this.Help.ShortLabel = Mono.Unix.Catalog.GetString("Help");
            w2.Add(this.Help, null);
            this.about = new Gtk.Action("about", Mono.Unix.Catalog.GetString("_About"), null, "gtk-about");
            this.about.ShortLabel = Mono.Unix.Catalog.GetString("_About");
            w2.Add(this.about, null);
            this.View = new Gtk.Action("View", Mono.Unix.Catalog.GetString("_View"), null, null);
            this.View.ShortLabel = Mono.Unix.Catalog.GetString("_View");
            w2.Add(this.View, null);
            this.Monitor = new Gtk.Action("Monitor", Mono.Unix.Catalog.GetString("_Monitor..."), Mono.Unix.Catalog.GetString("Show D-Bus Monitor to track events on the selected bus."), "gtk-network");
            this.Monitor.ShortLabel = Mono.Unix.Catalog.GetString("_Monitor");
            w2.Add(this.Monitor, "<Control>m");
            this.CustomBus = new Gtk.Action("CustomBus", Mono.Unix.Catalog.GetString("C_ustom Bus..."), null, null);
            this.CustomBus.ShortLabel = Mono.Unix.Catalog.GetString("C_ustom Bus...");
            w2.Add(this.CustomBus, null);
            this.Tools = new Gtk.Action("Tools", Mono.Unix.Catalog.GetString("_Tools"), null, null);
            this.Tools.ShortLabel = Mono.Unix.Catalog.GetString("_Tools");
            w2.Add(this.Tools, null);
            this.Languages = new Gtk.Action("Languages", Mono.Unix.Catalog.GetString("Languages"), null, null);
            this.Languages.ShortLabel = Mono.Unix.Catalog.GetString("Languages");
            w2.Add(this.Languages, null);
            this.C = new Gtk.ToggleAction("C", Mono.Unix.Catalog.GetString("C#"), null, null);
            this.C.ShortLabel = Mono.Unix.Catalog.GetString("C#");
            w2.Add(this.C, null);
            this.NewTabAction = new Gtk.Action("NewTabAction", Mono.Unix.Catalog.GetString("New Tab"), null, null);
            this.NewTabAction.ShortLabel = Mono.Unix.Catalog.GetString("New Bus");
            w2.Add(this.NewTabAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "DBusExplorer.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("D-Bus Explorer");
            this.Icon = Gdk.Pixbuf.LoadFromResource("dbus-explorer.png");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.AllowShrink = true;
            // Container child DBusExplorer.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='NewTabAction'/><menu action='SelectBus'><menuitem action='SessionBus'/><menuitem action='SystemBus'/><menuitem action='CustomBus'/></menu><menuitem action='quit1'/></menu><menu action='View'><menu action='Languages'><menuitem action='C'/></menu><menuitem action='Monitor'/></menu><menu action='Help'><menuitem action='about'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(5));
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Bus name : ");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.busCbCont = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.busCbCont.Name = "busCbCont";
            // Container child busCbCont.Gtk.Container+ContainerChild
            this.busCb = Gtk.ComboBox.NewText();
            this.busCb.Name = "busCb";
            this.busCbCont.Add(this.busCb);
            this.hbox1.Add(this.busCbCont);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.busCbCont]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment4 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment4.Name = "alignment4";
            this.alignment4.LeftPadding = ((uint)(62));
            this.alignment4.RightPadding = ((uint)(208));
            // Container child alignment4.Gtk.Container+ContainerChild
            this.spinnerBox = new Gtk.HBox();
            this.spinnerBox.Name = "spinnerBox";
            this.spinnerBox.Spacing = 6;
            // Container child spinnerBox.Gtk.Box+BoxChild
            this.spinnerAlign = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.spinnerAlign.Name = "spinnerAlign";
            this.spinnerBox.Add(this.spinnerAlign);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.spinnerBox[this.spinnerAlign]));
            w7.Position = 0;
            // Container child spinnerBox.Gtk.Box+BoxChild
            this.alignment6 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment6.Name = "alignment6";
            // Container child alignment6.Gtk.Container+ContainerChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Parsing ...");
            this.alignment6.Add(this.label4);
            this.spinnerBox.Add(this.alignment6);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.spinnerBox[this.alignment6]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            this.alignment4.Add(this.spinnerBox);
            this.hbox1.Add(this.alignment4);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment4]));
            w11.Position = 2;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            w12.Padding = ((uint)(1));
            // Container child vbox1.Gtk.Box+BoxChild
            this.buses_Nb = new Gtk.Notebook();
            this.buses_Nb.CanFocus = true;
            this.buses_Nb.Name = "buses_Nb";
            this.buses_Nb.CurrentPage = 0;
            // Notebook tab
            Gtk.Label w13 = new Gtk.Label();
            w13.Visible = true;
            this.buses_Nb.Add(w13);
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("(No Title)");
            this.buses_Nb.SetTabLabel(w13, this.label2);
            this.label2.ShowAll();
            this.vbox1.Add(this.buses_Nb);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox1[this.buses_Nb]));
            w14.Position = 2;
            // Container child vbox1.Gtk.Box+BoxChild
            this.statusbar1 = new Gtk.Statusbar();
            this.statusbar1.Name = "statusbar1";
            this.statusbar1.Spacing = 6;
            this.vbox1.Add(this.statusbar1);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
            w15.Position = 3;
            w15.Expand = false;
            w15.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 798;
            this.DefaultHeight = 679;
            this.Show();
            this.SessionBus.Activated += new System.EventHandler(this.OnSessionBusActivated);
            this.SystemBus.Activated += new System.EventHandler(this.OnSystemBusActivated);
            this.quit.Activated += new System.EventHandler(this.OnDeleteEvent);
            this.quit1.Activated += new System.EventHandler(this.OnDeleteEvent);
            this.about.Activated += new System.EventHandler(this.OnAboutActivated);
            this.Monitor.Activated += new System.EventHandler(this.OnMonitorActivated);
            this.CustomBus.Activated += new System.EventHandler(this.OnCustomBusActivated);
            this.NewTabAction.Activated += new System.EventHandler(this.OnNewTabActionActivated);
            this.buses_Nb.SwitchPage += new Gtk.SwitchPageHandler(this.OnBusesNbSwitchPage);
        }
    }
}
