// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    
    public partial class BusPageWidget {
        
        private Gtk.VPaned vpaned3;
        
        private Gtk.ScrolledWindow tvWindow;
        
        private Gtk.Alignment tvPlaceholder;
        
        private Gtk.Alignment informationViewPlaceholder;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.BusPageWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "DBusExplorer.BusPageWidget";
            // Container child DBusExplorer.BusPageWidget.Gtk.Container+ContainerChild
            this.vpaned3 = new Gtk.VPaned();
            this.vpaned3.CanFocus = true;
            this.vpaned3.Name = "vpaned3";
            this.vpaned3.Position = 120;
            // Container child vpaned3.Gtk.Paned+PanedChild
            this.tvWindow = new Gtk.ScrolledWindow();
            this.tvWindow.CanFocus = true;
            this.tvWindow.Name = "tvWindow";
            this.tvWindow.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.tvWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.tvWindow.BorderWidth = ((uint)(3));
            // Container child tvWindow.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.tvPlaceholder = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.tvPlaceholder.Name = "tvPlaceholder";
            w1.Add(this.tvPlaceholder);
            this.tvWindow.Add(w1);
            this.vpaned3.Add(this.tvWindow);
            Gtk.Paned.PanedChild w4 = ((Gtk.Paned.PanedChild)(this.vpaned3[this.tvWindow]));
            w4.Resize = false;
            // Container child vpaned3.Gtk.Paned+PanedChild
            this.informationViewPlaceholder = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.informationViewPlaceholder.Name = "informationViewPlaceholder";
            this.vpaned3.Add(this.informationViewPlaceholder);
            this.Add(this.vpaned3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
