// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    
    public partial class BusPageWidget {
        
        private Gtk.VBox vbox3;
        
        private Gtk.ScrolledWindow tvWindow;
        
        private Gtk.Alignment tvPlaceholder;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Alignment informationViewPlaceholder;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.BusPageWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "DBusExplorer.BusPageWidget";
            // Container child DBusExplorer.BusPageWidget.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.tvWindow = new Gtk.ScrolledWindow();
            this.tvWindow.CanFocus = true;
            this.tvWindow.Name = "tvWindow";
            this.tvWindow.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.tvWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.tvWindow.BorderWidth = ((uint)(3));
            // Container child tvWindow.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.tvPlaceholder = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.tvPlaceholder.Name = "tvPlaceholder";
            w1.Add(this.tvPlaceholder);
            this.tvWindow.Add(w1);
            this.vbox3.Add(this.tvWindow);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.tvWindow]));
            w4.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.informationViewPlaceholder = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.informationViewPlaceholder.Name = "informationViewPlaceholder";
            this.vbox4.Add(this.informationViewPlaceholder);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox4[this.informationViewPlaceholder]));
            w5.Position = 0;
            w5.Expand = false;
            this.vbox3.Add(this.vbox4);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
            w6.Position = 1;
            w6.Expand = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
