// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    
    public partial class DBusMonitor {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.CheckButton meths_cb;
        
        private Gtk.CheckButton signals_cb;
        
        private Gtk.CheckButton props_cb;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView monitor_tv;
        
        private Gtk.Button buttonCancel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.DBusMonitor
            this.Name = "DBusExplorer.DBusMonitor";
            this.Title = Mono.Unix.Catalog.GetString("D-Bus Monitor");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child DBusExplorer.DBusMonitor.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.TopPadding = ((uint)(10));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.meths_cb = new Gtk.CheckButton();
            this.meths_cb.CanFocus = true;
            this.meths_cb.Name = "meths_cb";
            this.meths_cb.Label = Mono.Unix.Catalog.GetString("Show Methods");
            this.meths_cb.DrawIndicator = true;
            this.meths_cb.UseUnderline = true;
            this.hbox2.Add(this.meths_cb);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.meths_cb]));
            w2.Position = 0;
            w2.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.signals_cb = new Gtk.CheckButton();
            this.signals_cb.CanFocus = true;
            this.signals_cb.Name = "signals_cb";
            this.signals_cb.Label = Mono.Unix.Catalog.GetString("Show Signals");
            this.signals_cb.DrawIndicator = true;
            this.signals_cb.UseUnderline = true;
            this.hbox2.Add(this.signals_cb);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.signals_cb]));
            w3.Position = 1;
            w3.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.props_cb = new Gtk.CheckButton();
            this.props_cb.CanFocus = true;
            this.props_cb.Name = "props_cb";
            this.props_cb.Label = Mono.Unix.Catalog.GetString("Show Properties");
            this.props_cb.DrawIndicator = true;
            this.props_cb.UseUnderline = true;
            this.hbox2.Add(this.props_cb);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.props_cb]));
            w4.Position = 2;
            w4.Fill = false;
            this.alignment1.Add(this.hbox2);
            this.vbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.VscrollbarPolicy = ((Gtk.PolicyType)(1));
            this.GtkScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.GtkScrolledWindow.BorderWidth = ((uint)(6));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.monitor_tv = new Gtk.TextView();
            this.monitor_tv.CanFocus = true;
            this.monitor_tv.Name = "monitor_tv";
            this.GtkScrolledWindow.Add(this.monitor_tv);
            this.vbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
            w8.Position = 1;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w9.Position = 0;
            // Internal child DBusExplorer.DBusMonitor.ActionArea
            Gtk.HButtonBox w10 = this.ActionArea;
            w10.Name = "dialog1_ActionArea";
            w10.Spacing = 6;
            w10.BorderWidth = ((uint)(5));
            w10.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-close";
            this.AddActionWidget(this.buttonCancel, -7);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonCancel]));
            w11.Expand = false;
            w11.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 705;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
