// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DBusExplorer {
    
    
    public partial class MainWindow {
        
        private Gtk.Action File;
        
        private Gtk.Action SelectBus;
        
        private Gtk.RadioAction SessionBus;
        
        private Gtk.RadioAction SystemBus;
        
        private Gtk.Action quit;
        
        private Gtk.Action quit1;
        
        private Gtk.Action Help;
        
        private Gtk.Action about;
        
        private Gtk.Action View;
        
        private Gtk.Action Monitor;
        
        private Gtk.Action CustomBus;
        
        private Gtk.Action Tools;
        
        private Gtk.Action LanguageRepresentations;
        
        private Gtk.Action CpdeGenerator;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Alignment busCbCont;
        
        private Gtk.ComboBox busCb;
        
        private Gtk.Alignment alignment4;
        
        private Gtk.HBox spinnerBox;
        
        private Gtk.Alignment spinnerAlign;
        
        private Gtk.Alignment alignment6;
        
        private Gtk.Label label4;
        
        private Gtk.VPaned vpaned2;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView tv;
        
        private Gtk.Expander expander2;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Alignment alignment5;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Image symbolImage;
        
        private Gtk.Alignment alignment7;
        
        private Gtk.Label specstyleDecl;
        
        private Gtk.Alignment alignment8;
        
        private Gtk.HBox hbox6;
        
        private Gtk.Label label5;
        
        private Gtk.Label cstyleDecl;
        
        private Gtk.HBox hbox7;
        
        private Gtk.Label label6;
        
        private Gtk.Label informationLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DBusExplorer.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("_File"), null, null);
            this.File.ShortLabel = Mono.Unix.Catalog.GetString("_File");
            w2.Add(this.File, null);
            this.SelectBus = new Gtk.Action("SelectBus", Mono.Unix.Catalog.GetString("_Select Bus"), null, null);
            this.SelectBus.ShortLabel = Mono.Unix.Catalog.GetString("Select Bus");
            w2.Add(this.SelectBus, null);
            this.SessionBus = new Gtk.RadioAction("SessionBus", Mono.Unix.Catalog.GetString("S_ession Bus"), null, null, 0);
            this.SessionBus.Group = new GLib.SList(System.IntPtr.Zero);
            this.SessionBus.ShortLabel = Mono.Unix.Catalog.GetString("Session Bus");
            w2.Add(this.SessionBus, null);
            this.SystemBus = new Gtk.RadioAction("SystemBus", Mono.Unix.Catalog.GetString("S_ystem Bus"), null, null, 0);
            this.SystemBus.Group = this.SessionBus.Group;
            this.SystemBus.ShortLabel = Mono.Unix.Catalog.GetString("System Bus");
            w2.Add(this.SystemBus, null);
            this.quit = new Gtk.Action("quit", Mono.Unix.Catalog.GetString("_Quitter"), null, "gtk-quit");
            this.quit.ShortLabel = Mono.Unix.Catalog.GetString("_Quitter");
            w2.Add(this.quit, null);
            this.quit1 = new Gtk.Action("quit1", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
            this.quit1.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
            w2.Add(this.quit1, null);
            this.Help = new Gtk.Action("Help", Mono.Unix.Catalog.GetString("_Help"), null, null);
            this.Help.ShortLabel = Mono.Unix.Catalog.GetString("Help");
            w2.Add(this.Help, null);
            this.about = new Gtk.Action("about", Mono.Unix.Catalog.GetString("_About"), null, "gtk-about");
            this.about.ShortLabel = Mono.Unix.Catalog.GetString("_About");
            w2.Add(this.about, null);
            this.View = new Gtk.Action("View", Mono.Unix.Catalog.GetString("_View"), null, null);
            this.View.ShortLabel = Mono.Unix.Catalog.GetString("_View");
            w2.Add(this.View, null);
            this.Monitor = new Gtk.Action("Monitor", Mono.Unix.Catalog.GetString("_Monitor..."), Mono.Unix.Catalog.GetString("Show D-Bus Monitor to track events on the selected bus."), "gtk-network");
            this.Monitor.ShortLabel = Mono.Unix.Catalog.GetString("_Monitor");
            w2.Add(this.Monitor, "<Control>m");
            this.CustomBus = new Gtk.Action("CustomBus", Mono.Unix.Catalog.GetString("C_ustom Bus..."), null, null);
            this.CustomBus.ShortLabel = Mono.Unix.Catalog.GetString("C_ustom Bus...");
            w2.Add(this.CustomBus, null);
            this.Tools = new Gtk.Action("Tools", Mono.Unix.Catalog.GetString("_Tools"), null, null);
            this.Tools.ShortLabel = Mono.Unix.Catalog.GetString("_Tools");
            w2.Add(this.Tools, null);
            this.LanguageRepresentations = new Gtk.Action("LanguageRepresentations", Mono.Unix.Catalog.GetString("Language representations ..."), null, "gtk-select-all");
            this.LanguageRepresentations.ShortLabel = Mono.Unix.Catalog.GetString("Language representations ...");
            w2.Add(this.LanguageRepresentations, null);
            this.CpdeGenerator = new Gtk.Action("CpdeGenerator", Mono.Unix.Catalog.GetString("Code Generator..."), null, "gtk-convert");
            this.CpdeGenerator.ShortLabel = Mono.Unix.Catalog.GetString("Code Generator...");
            w2.Add(this.CpdeGenerator, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "DBusExplorer.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("D-Bus Explorer");
            this.Icon = Gdk.Pixbuf.LoadFromResource("icon.png");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.AllowShrink = true;
            this.DefaultWidth = 900;
            this.DefaultHeight = 700;
            // Container child DBusExplorer.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menu action='SelectBus'><menuitem action='SessionBus'/><menuitem action='SystemBus'/><menuitem action='CustomBus'/></menu><menuitem action='quit1'/></menu><menu action='View'><menuitem action='Monitor'/></menu><menu action='Help'><menuitem action='about'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(5));
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Bus name : ");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.busCbCont = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.busCbCont.Name = "busCbCont";
            // Container child busCbCont.Gtk.Container+ContainerChild
            this.busCb = Gtk.ComboBox.NewText();
            this.busCb.Name = "busCb";
            this.busCbCont.Add(this.busCb);
            this.hbox1.Add(this.busCbCont);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.busCbCont]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment4 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment4.Name = "alignment4";
            this.alignment4.LeftPadding = ((uint)(62));
            this.alignment4.RightPadding = ((uint)(208));
            // Container child alignment4.Gtk.Container+ContainerChild
            this.spinnerBox = new Gtk.HBox();
            this.spinnerBox.Name = "spinnerBox";
            this.spinnerBox.Spacing = 6;
            // Container child spinnerBox.Gtk.Box+BoxChild
            this.spinnerAlign = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.spinnerAlign.Name = "spinnerAlign";
            this.spinnerBox.Add(this.spinnerAlign);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.spinnerBox[this.spinnerAlign]));
            w7.Position = 0;
            // Container child spinnerBox.Gtk.Box+BoxChild
            this.alignment6 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment6.Name = "alignment6";
            // Container child alignment6.Gtk.Container+ContainerChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Parsing ...");
            this.alignment6.Add(this.label4);
            this.spinnerBox.Add(this.alignment6);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.spinnerBox[this.alignment6]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            this.alignment4.Add(this.spinnerBox);
            this.hbox1.Add(this.alignment4);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment4]));
            w11.Position = 2;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            w12.Padding = ((uint)(1));
            // Container child vbox1.Gtk.Box+BoxChild
            this.vpaned2 = new Gtk.VPaned();
            this.vpaned2.CanFocus = true;
            this.vpaned2.Name = "vpaned2";
            this.vpaned2.Position = 500;
            // Container child vpaned2.Gtk.Paned+PanedChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            this.scrolledwindow1.BorderWidth = ((uint)(3));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.tv = new Gtk.TreeView();
            this.tv.CanFocus = true;
            this.tv.Name = "tv";
            this.tv.Reorderable = true;
            this.tv.HeadersClickable = true;
            this.scrolledwindow1.Add(this.tv);
            this.vpaned2.Add(this.scrolledwindow1);
            Gtk.Paned.PanedChild w14 = ((Gtk.Paned.PanedChild)(this.vpaned2[this.scrolledwindow1]));
            w14.Resize = false;
            w14.Shrink = false;
            // Container child vpaned2.Gtk.Paned+PanedChild
            this.expander2 = new Gtk.Expander(null);
            this.expander2.CanFocus = true;
            this.expander2.Name = "expander2";
            this.expander2.Expanded = true;
            this.expander2.Spacing = 2;
            this.expander2.BorderWidth = ((uint)(5));
            // Container child expander2.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            this.vbox3.BorderWidth = ((uint)(6));
            // Container child vbox3.Gtk.Box+BoxChild
            this.alignment5 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment5.Name = "alignment5";
            this.alignment5.LeftPadding = ((uint)(44));
            this.alignment5.TopPadding = ((uint)(7));
            this.alignment5.BottomPadding = ((uint)(8));
            // Container child alignment5.Gtk.Container+ContainerChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.symbolImage = new Gtk.Image();
            this.symbolImage.Name = "symbolImage";
            this.hbox5.Add(this.symbolImage);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox5[this.symbolImage]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.alignment7 = new Gtk.Alignment(0.4F, 0.5F, 1F, 1F);
            this.alignment7.Name = "alignment7";
            this.alignment7.LeftPadding = ((uint)(10));
            // Container child alignment7.Gtk.Container+ContainerChild
            this.specstyleDecl = new Gtk.Label();
            this.specstyleDecl.Name = "specstyleDecl";
            this.specstyleDecl.LabelProp = "";
            this.specstyleDecl.UseMarkup = true;
            this.alignment7.Add(this.specstyleDecl);
            this.hbox5.Add(this.alignment7);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox5[this.alignment7]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            this.alignment5.Add(this.hbox5);
            this.vbox3.Add(this.alignment5);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox3[this.alignment5]));
            w19.Position = 0;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.alignment8 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment8.Name = "alignment8";
            this.alignment8.LeftPadding = ((uint)(7));
            this.alignment8.TopPadding = ((uint)(4));
            this.alignment8.BottomPadding = ((uint)(7));
            // Container child alignment8.Gtk.Container+ContainerChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("C# Style : ");
            this.hbox6.Add(this.label5);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox6[this.label5]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.cstyleDecl = new Gtk.Label();
            this.cstyleDecl.Name = "cstyleDecl";
            this.cstyleDecl.LabelProp = "";
            this.hbox6.Add(this.cstyleDecl);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox6[this.cstyleDecl]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            this.alignment8.Add(this.hbox6);
            this.vbox3.Add(this.alignment8);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox3[this.alignment8]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            this.expander2.Add(this.vbox3);
            this.hbox7 = new Gtk.HBox();
            this.hbox7.Name = "hbox7";
            this.hbox7.Spacing = 1;
            // Container child hbox7.Gtk.Box+BoxChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("<b>Informations on : </b>");
            this.label6.UseMarkup = true;
            this.hbox7.Add(this.label6);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox7[this.label6]));
            w25.Position = 0;
            w25.Expand = false;
            w25.Fill = false;
            // Container child hbox7.Gtk.Box+BoxChild
            this.informationLabel = new Gtk.Label();
            this.informationLabel.Name = "informationLabel";
            this.informationLabel.LabelProp = "";
            this.hbox7.Add(this.informationLabel);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox7[this.informationLabel]));
            w26.Position = 1;
            w26.Expand = false;
            w26.Fill = false;
            this.expander2.LabelWidget = this.hbox7;
            this.vpaned2.Add(this.expander2);
            this.vbox1.Add(this.vpaned2);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox1[this.vpaned2]));
            w28.Position = 2;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.SessionBus.Activated += new System.EventHandler(this.OnSessionBusActivated);
            this.SystemBus.Activated += new System.EventHandler(this.OnSystemBusActivated);
            this.quit.Activated += new System.EventHandler(this.OnDeleteEvent);
            this.quit1.Activated += new System.EventHandler(this.OnDeleteEvent);
            this.about.Activated += new System.EventHandler(this.OnAboutActivated);
            this.Monitor.Activated += new System.EventHandler(this.OnMonitorActivated);
            this.CustomBus.Activated += new System.EventHandler(this.OnCustomBusActivated);
        }
    }
}
