// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action File;
    
    private Gtk.Action SelectBus;
    
    private Gtk.RadioAction SessionBus;
    
    private Gtk.RadioAction SystemBus;
    
    private Gtk.Action quit;
    
    private Gtk.Action quit1;
    
    private Gtk.Action Help;
    
    private Gtk.Action about;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Label label1;
    
    private Gtk.Alignment busCbCont;
    
    private Gtk.ComboBox busCb;
    
    private Gtk.Alignment alignment4;
    
    private Gtk.HBox spinnerBox;
    
    private Gtk.Alignment spinnerAlign;
    
    private Gtk.Alignment alignment6;
    
    private Gtk.Label label4;
    
    private Gtk.VPaned vpaned2;
    
    private Gtk.ScrolledWindow scrolledwindow1;
    
    private Gtk.TreeView tv;
    
    private Gtk.Expander expander1;
    
    private Gtk.VBox vbox2;
    
    private Gtk.Alignment alignment1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Image symbolImage;
    
    private Gtk.Alignment alignment2;
    
    private Gtk.Label specstyleDecl;
    
    private Gtk.Alignment alignment3;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label label3;
    
    private Gtk.Label cstyleDecl;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Label label2;
    
    private Gtk.Label informationLabel;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("_File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("_File");
        w2.Add(this.File, null);
        this.SelectBus = new Gtk.Action("SelectBus", Mono.Unix.Catalog.GetString("Select Bus"), null, null);
        this.SelectBus.ShortLabel = Mono.Unix.Catalog.GetString("Select Bus");
        w2.Add(this.SelectBus, null);
        this.SessionBus = new Gtk.RadioAction("SessionBus", Mono.Unix.Catalog.GetString("Session Bus"), null, null, 0);
        this.SessionBus.Group = new GLib.SList(System.IntPtr.Zero);
        this.SessionBus.ShortLabel = Mono.Unix.Catalog.GetString("Session Bus");
        w2.Add(this.SessionBus, null);
        this.SystemBus = new Gtk.RadioAction("SystemBus", Mono.Unix.Catalog.GetString("System Bus"), null, null, 0);
        this.SystemBus.Group = this.SessionBus.Group;
        this.SystemBus.ShortLabel = Mono.Unix.Catalog.GetString("System Bus");
        w2.Add(this.SystemBus, null);
        this.quit = new Gtk.Action("quit", Mono.Unix.Catalog.GetString("_Quitter"), null, "gtk-quit");
        this.quit.ShortLabel = Mono.Unix.Catalog.GetString("_Quitter");
        w2.Add(this.quit, null);
        this.quit1 = new Gtk.Action("quit1", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.quit1.ShortLabel = Mono.Unix.Catalog.GetString("_Quitter");
        w2.Add(this.quit1, null);
        this.Help = new Gtk.Action("Help", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.Help.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w2.Add(this.Help, null);
        this.about = new Gtk.Action("about", Mono.Unix.Catalog.GetString("_About"), null, "gtk-about");
        this.about.ShortLabel = Mono.Unix.Catalog.GetString("_About");
        w2.Add(this.about, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("D-Bus Explorer");
        this.Icon = Gdk.Pixbuf.LoadFromResource("icon.png");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.AllowShrink = true;
        this.DefaultWidth = 800;
        this.DefaultHeight = 600;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menu action='SelectBus'><menuitem action='SessionBus'/><menuitem action='SystemBus'/></menu><menuitem action='quit1'/></menu><menu action='Help'><menuitem action='about'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        this.hbox1.BorderWidth = ((uint)(5));
        // Container child hbox1.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Bus name : ");
        this.hbox1.Add(this.label1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.busCbCont = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.busCbCont.Name = "busCbCont";
        // Container child busCbCont.Gtk.Container+ContainerChild
        this.busCb = Gtk.ComboBox.NewText();
        this.busCb.Name = "busCb";
        this.busCbCont.Add(this.busCb);
        this.hbox1.Add(this.busCbCont);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.busCbCont]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.alignment4 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment4.Name = "alignment4";
        this.alignment4.LeftPadding = ((uint)(62));
        this.alignment4.RightPadding = ((uint)(208));
        // Container child alignment4.Gtk.Container+ContainerChild
        this.spinnerBox = new Gtk.HBox();
        this.spinnerBox.Name = "spinnerBox";
        this.spinnerBox.Spacing = 6;
        // Container child spinnerBox.Gtk.Box+BoxChild
        this.spinnerAlign = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.spinnerAlign.Name = "spinnerAlign";
        this.spinnerBox.Add(this.spinnerAlign);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.spinnerBox[this.spinnerAlign]));
        w7.Position = 0;
        // Container child spinnerBox.Gtk.Box+BoxChild
        this.alignment6 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment6.Name = "alignment6";
        // Container child alignment6.Gtk.Container+ContainerChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Parsing ...");
        this.alignment6.Add(this.label4);
        this.spinnerBox.Add(this.alignment6);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.spinnerBox[this.alignment6]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        this.alignment4.Add(this.spinnerBox);
        this.hbox1.Add(this.alignment4);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment4]));
        w11.Position = 2;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w12.Position = 1;
        w12.Expand = false;
        w12.Fill = false;
        w12.Padding = ((uint)(1));
        // Container child vbox1.Gtk.Box+BoxChild
        this.vpaned2 = new Gtk.VPaned();
        this.vpaned2.CanFocus = true;
        this.vpaned2.Name = "vpaned2";
        this.vpaned2.Position = 347;
        // Container child vpaned2.Gtk.Paned+PanedChild
        this.scrolledwindow1 = new Gtk.ScrolledWindow();
        this.scrolledwindow1.CanFocus = true;
        this.scrolledwindow1.Name = "scrolledwindow1";
        this.scrolledwindow1.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(2));
        this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
        this.scrolledwindow1.BorderWidth = ((uint)(3));
        // Container child scrolledwindow1.Gtk.Container+ContainerChild
        this.tv = new Gtk.TreeView();
        this.tv.CanFocus = true;
        this.tv.Name = "tv";
        this.tv.HeadersVisible = false;
        this.tv.HeadersClickable = true;
        this.scrolledwindow1.Add(this.tv);
        this.vpaned2.Add(this.scrolledwindow1);
        Gtk.Paned.PanedChild w14 = ((Gtk.Paned.PanedChild)(this.vpaned2[this.scrolledwindow1]));
        w14.Resize = false;
        w14.Shrink = false;
        // Container child vpaned2.Gtk.Paned+PanedChild
        this.expander1 = new Gtk.Expander(null);
        this.expander1.CanFocus = true;
        this.expander1.Name = "expander1";
        this.expander1.Expanded = true;
        this.expander1.Spacing = 2;
        this.expander1.BorderWidth = ((uint)(6));
        // Container child expander1.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        this.vbox2.BorderWidth = ((uint)(6));
        // Container child vbox2.Gtk.Box+BoxChild
        this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment1.Name = "alignment1";
        this.alignment1.LeftPadding = ((uint)(44));
        this.alignment1.TopPadding = ((uint)(7));
        this.alignment1.BottomPadding = ((uint)(8));
        // Container child alignment1.Gtk.Container+ContainerChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.symbolImage = new Gtk.Image();
        this.symbolImage.Name = "symbolImage";
        this.hbox2.Add(this.symbolImage);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox2[this.symbolImage]));
        w15.Position = 0;
        w15.Expand = false;
        w15.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.alignment2 = new Gtk.Alignment(0.4F, 0.5F, 1F, 1F);
        this.alignment2.Name = "alignment2";
        this.alignment2.LeftPadding = ((uint)(10));
        // Container child alignment2.Gtk.Container+ContainerChild
        this.specstyleDecl = new Gtk.Label();
        this.specstyleDecl.Name = "specstyleDecl";
        this.specstyleDecl.LabelProp = "";
        this.specstyleDecl.UseMarkup = true;
        this.alignment2.Add(this.specstyleDecl);
        this.hbox2.Add(this.alignment2);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox2[this.alignment2]));
        w17.Position = 1;
        w17.Expand = false;
        w17.Fill = false;
        this.alignment1.Add(this.hbox2);
        this.vbox2.Add(this.alignment1);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
        w19.Position = 0;
        w19.Expand = false;
        w19.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.alignment3 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
        this.alignment3.Name = "alignment3";
        this.alignment3.LeftPadding = ((uint)(7));
        this.alignment3.TopPadding = ((uint)(4));
        this.alignment3.BottomPadding = ((uint)(7));
        // Container child alignment3.Gtk.Container+ContainerChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("C# Style : ");
        this.hbox3.Add(this.label3);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox3[this.label3]));
        w20.Position = 0;
        w20.Expand = false;
        w20.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.cstyleDecl = new Gtk.Label();
        this.cstyleDecl.Name = "cstyleDecl";
        this.cstyleDecl.LabelProp = "";
        this.hbox3.Add(this.cstyleDecl);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox3[this.cstyleDecl]));
        w21.Position = 1;
        w21.Expand = false;
        w21.Fill = false;
        this.alignment3.Add(this.hbox3);
        this.vbox2.Add(this.alignment3);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment3]));
        w23.Position = 1;
        w23.Expand = false;
        w23.Fill = false;
        this.expander1.Add(this.vbox2);
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 1;
        // Container child hbox4.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("<b>Informations on : </b>");
        this.label2.UseMarkup = true;
        this.hbox4.Add(this.label2);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox4[this.label2]));
        w25.Position = 0;
        w25.Expand = false;
        w25.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.informationLabel = new Gtk.Label();
        this.informationLabel.Name = "informationLabel";
        this.informationLabel.LabelProp = "";
        this.hbox4.Add(this.informationLabel);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox4[this.informationLabel]));
        w26.Position = 1;
        w26.Expand = false;
        w26.Fill = false;
        this.expander1.LabelWidget = this.hbox4;
        this.vpaned2.Add(this.expander1);
        this.vbox1.Add(this.vpaned2);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox1[this.vpaned2]));
        w28.Position = 2;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.Show();
        this.SessionBus.Activated += new System.EventHandler(this.OnSessionBusActivated);
        this.SystemBus.Activated += new System.EventHandler(this.OnSystemBusActivated);
        this.quit.Activated += new System.EventHandler(this.OnDeleteEvent);
        this.quit1.Activated += new System.EventHandler(this.OnDeleteEvent);
    }
}
